[phases.setup]
nixPkgs = ["nodejs-18_x", "python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
  "npm install",
  "npm run build",
  "python -m venv venv",
  "source venv/bin/activate && pip install --upgrade pip setuptools wheel",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "bash start.sh"

